[tool.poetry]
name = "edge"
version = "0.1.0"
description = ""
authors = ["Mohit Hulse"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
modal = "^0.52.3439"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
